apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyterlab.fullname" . }}
  labels:
    {{- include "jupyterlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jupyterlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterlab.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: notebook-data
          persistentVolumeClaim:
            claimName: {{ .Values.fullnameOverride }}-pvc
      initContainers:
        - name: copy-data
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command:
            - /bin/sh
            - -c
            - "stat /tmp/notebook/welcome_to_cloudbench.ipynb 1>/dev/null 2>&1  && echo 'Data already present on volume' || cp -R /notebook/* /tmp/notebook/"
          volumeMounts:
            - mountPath: /tmp/notebook
              name: notebook-data
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jupyterlab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: S3_BUCKET_NAME
              value: "{{ .Values.s3BucketName }}"
          ports:
            - name: http
              containerPort: 8888 
              protocol: TCP
          args: ["jupyter lab --allow-root --ip 0.0.0.0 --NotebookApp.password={{ .Values.password }}"]
          command: ["sh", "-c"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /notebook
              name: notebook-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
